// scripts/generate-changelog-json.ts
//
// Regenerates public/changelog.json from CHANGELOG.md. public/ is copied
// verbatim into every build's output root by WXT (same as public/icons/**),
// so this lands the file next to whats-new.html in all 4 build combinations
// automatically — no per-target/per-browser logic needed.
//
// Regeneration is wired two ways, deliberately overlapping:
//   1. Chained in front of every npm script that invokes wxt prepare/build/dev
//      (package.json's postinstall and dev/build*/zip* scripts). The postinstall
//      one is load-bearing and can't be replaced by a hook: WXT's PublicPath
//      type (browser.runtime.getURL()'s param type) is generated by scanning
//      public/'s actual on-disk contents at `wxt prepare` time, so
//      public/changelog.json must already exist on disk before that scan runs,
//      including the very first `npm install` on a fresh clone
//      (public/changelog.json is gitignored — fully derived).
//   2. A `build:before` hook in wxt.config.ts, which imports generateChangelogJson
//      from here and runs it before every `wxt build`/`wxt zip`/`wxt dev` —
//      covering any caller that invokes wxt directly and skips the npm-script
//      chain, e.g. a `wxt zip` run after cut-release.ts has promoted
//      CHANGELOG.md's [Unreleased] section (the v1.2.0 release shipped a
//      changelog.json missing the just-cut version this way).

import { argv } from "node:process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { parseChangelog } from "./changelog.ts";

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));

export function generateChangelogJson(repoRoot: string = REPO_ROOT): void {
  const markdown = readFileSync(`${repoRoot}/CHANGELOG.md`, "utf8");
  const entries = parseChangelog(markdown);
  writeFileSync(`${repoRoot}/public/changelog.json`, JSON.stringify(entries, null, 2) + "\n");
}

// Only self-run when invoked directly (`node scripts/generate-changelog-json.ts`,
// as postinstall and the npm scripts do) — not when imported by wxt.config.ts's
// build:before hook, which calls generateChangelogJson() itself.
if (fileURLToPath(import.meta.url) === argv[1]) {
  generateChangelogJson();
}
