// scripts/generate-changelog-json.ts
//
// Regenerates public/changelog.json from CHANGELOG.md. public/ is copied
// verbatim into every build's output root by WXT (same as public/icons/**),
// so this lands the file next to whats-new.html in all 4 build combinations
// automatically — no per-target/per-browser logic needed.
//
// Chained in front of every command that invokes wxt prepare/build/dev (see
// package.json's postinstall and dev/build* scripts) rather than wired via a
// WXT build hook: WXT's PublicPath type (browser.runtime.getURL()'s param
// type) is generated by scanning public/'s actual on-disk contents at `wxt
// prepare` time, so public/changelog.json must already exist on disk before
// that scan runs, every time, including the very first `npm install` on a
// fresh clone (public/changelog.json is gitignored — fully derived).

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { parseChangelog } from "./changelog.ts";

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));

export function generateChangelogJson(repoRoot: string = REPO_ROOT): void {
  const markdown = readFileSync(`${repoRoot}/CHANGELOG.md`, "utf8");
  const entries = parseChangelog(markdown);
  writeFileSync(`${repoRoot}/public/changelog.json`, JSON.stringify(entries, null, 2) + "\n");
}

generateChangelogJson();
